[package]
name = "my_ssg_with_ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
serde_yaml = "0.8.17"
pulldown-cmark = "0.8.0"
tera = "1.12.0"
